#
# Copyright Â© [2021] Dell Inc. or its subsidiaries.
# All Rights Reserved.
#
# This software contains the intellectual property of Dell Inc.
# or is licensed to Dell Inc. from third parties. Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of Dell Inc. or its subsidiaries.
#
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "influxdb-operator.fullname" . }}-confd-template
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "influxdb-operator.labels" . | indent 4}}
data:
  http.conf.toml: |+
    [template]
    src = "http.conf.tmpl"
    dest = "/etc/nginx/http.conf"
    keys = [
        "/replicas_f",
    ]
    reload_cmd = "pkill nginx"
  stream.conf.toml: |+
    [template]
    src = "stream.conf.tmpl"
    dest = "/etc/nginx/stream.conf"
    keys = [
        "/replicas_f",
    ]
    reload_cmd = "pkill nginx"