---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "influxdb-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "influxdb-operator.labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "influxdb-operator.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "influxdb-operator.labels" . | indent 8}}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "influxdb-operator.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "common-monitoring-lib.monitoring_registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.monitoring_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
{{ include "common-monitoring-lib.resources" (dict "top" . "micro" "100Mi" "small" "200Mi" "medium" "306Mi" "large" "306Mi") | indent 12}}
          command: ["bash"]
          args: ["-c", "{{ include "common-monitoring-lib.command" . }} ./manager --enable-leader-election"]
          env:
            - name: WATCH_NAMESPACE
{{- if eq .Values.global.watchAllNamespaces true }}
              value: ""
{{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
          volumeMounts:
          - mountPath: /crash-dump
            name: crash-dump
      volumes:
      - name: crash-dump
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
