---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "influxdb-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "influxdb-operator.labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "influxdb-operator.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "influxdb-operator.labels" . | indent 8}}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
        {{- if .Values.global.use_vault_for_ssl }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-requests-cpu: ""
        vault.hashicorp.com/agent-limits-cpu: ""
        vault.hashicorp.com/agent-inject-secret-influxdb_client.crt: "intermediate_pki/issue/intermediate_pki_issuer"
        vault.hashicorp.com/agent-inject-template-influxdb_client.crt: |
          {{`{{`}}- with secret "intermediate_pki/issue/intermediate_pki_issuer" "common_name={{ include "influxdb-operator.fullname" . }}-influxdb-client.{{ .Release.Namespace }}.svc.cluster.local" {{`}}`}}
          {{`{{`}} .Data.certificate {{`}}`}}
          {{`{{`}}- end {{`}}`}}
        vault.hashicorp.com/agent-inject-secret-influxdb_client.key: "intermediate_pki/issue/intermediate_pki_issuer"
        vault.hashicorp.com/agent-inject-template-influxdb_client.key: |
          {{`{{`}}- with secret "intermediate_pki/issue/intermediate_pki_issuer" "common_name={{ include "influxdb-operator.fullname" . }}-influxdb-client.{{ .Release.Namespace }}.svc.cluster.local" {{`}}`}}
          {{`{{`}} .Data.private_key {{`}}`}}
          {{`{{`}}- end {{`}}`}}
        vault.hashicorp.com/agent-inject-secret-trusted_influxdb_server_ca.crt: "intermediate_pki/issue/intermediate_pki_issuer"
        vault.hashicorp.com/agent-inject-template-trusted_influxdb_server_ca.crt: |
          {{`{{`}}- with secret "intermediate_pki/issue/intermediate_pki_issuer" "common_name={{ include "influxdb-operator.fullname" . }}-influxdb-client.{{ .Release.Namespace }}.svc.cluster.local" {{`}}`}}
          {{`{{`}}- range $cert := .Data.ca_chain {{`}}`}}
          {{`{{`}} $cert {{`}}`}}
          {{`{{`}}- end {{`}}`}}
          {{`{{`}}- end {{`}}`}}
        vault.hashicorp.com/role: "vault_requester"
        vault.hashicorp.com/tls-skip-verify: "true"
        {{- end }}
    spec:
      shareProcessNamespace: true
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "influxdb-operator.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "common-monitoring-lib.monitoring_registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.monitoring_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
{{ include "common-monitoring-lib.resources" (dict "top" . "micro" "100Mi" "small" "200Mi" "medium" "306Mi" "large" "306Mi") | indent 12}}
          command: ["bash"]
          args: ["-c", "{{ include "common-monitoring-lib.command" . }} ./manager --enable-leader-election"]
          env:
            - name: WATCH_NAMESPACE
{{- if eq .Values.global.watchAllNamespaces true }}
              value: ""
{{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- end }}
          volumeMounts:
          - mountPath: /crash-dump
            name: crash-dump
      {{- if .Values.global.tls_enabled }}
        - name: nginx
          image: "{{ include "common-monitoring-lib.monitoring_registry" . }}/nginx:{{ .Values.global.monitoring_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: nginx-config
            subPath: nginx.conf
          - mountPath: /etc/nginx/conf.d
            name: config
          - mountPath: /etc/confd_flex/templates
            name: configs-template
          - mountPath: /etc/confd_flex/conf.d
            name: configs-confd-template
          {{- if not .Values.global.use_vault_for_ssl }}
          - mountPath: /etc/nginx/cert
            name: cert
          {{- end }}
          - mountPath: /crash-dump
            name: crash-dump
{{ include "common-monitoring-lib.confd_sidecar_container" (dict "top" . "app_container_name" "nginx") | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.global.tls_enabled }}
      - name: nginx-config
        configMap:
          name: {{ template "influxdb-operator.fullname" . }}-nginx
      - name: configs-template
        configMap:
          name: {{ template "influxdb-operator.fullname" . }}-nginx-context
      - name: configs-confd-template
        configMap:
          name: {{ include "influxdb-operator.fullname" . }}-confd-template
      - name: influxdb-replicas-config
        configMap:
          name: {{ include "common-monitoring-lib.influxdb_replicas_config_map_name" . }}
      - name: config
        emptyDir: {}
      {{- if not .Values.global.use_vault_for_ssl }}
      - name: cert
        configMap:
          name: {{ .Release.Name }}-cert
      {{- end }}
      {{- end }}
      - name: crash-dump
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
