---
# Default values for ecs-flex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These global settings relate to both the ECS Flex operator as well as the
# Zookeeper Operator subchart
global:
  # Name of the target platform
  # By setting this value all necessary resources for ecs-flex will be created and configured accordingly.
  # Valid values are
  # "VMware" - VMWare Persistent Services Platform
  # "Vmware-PKS" - PKS platform with vSphere UI integration
  # "Atlantic" - Project Atlantic Bare-Metal Kubernetes platform
  # "Default" - All others
  platform: Default

  # Name of a Kubernetes secret with Docker credentials for the private registry
  # registrySecret: ecs-flex-registry

  # The private docker registry hosting containers for ECS Flex
  registry: objectscale

  # Default: true == Watch ALL namespaces
  watchAllNamespaces: true

# The default docker tag and pull policy for helm-controller services
tag: 0.70.3
pullPolicy: IfNotPresent

image:
  repository: install-controller
  # tag: stable
  # pullPolicy: IfNotPresent

# This will create the graphql container with the debug image tag. debug image will always be {{image.tag}}-debug
# also, this will expose port 40000 as debug port for debugging the application remotely in the cluster itself
debug: false

service:

  # Type of Kubernetes service: ClusterIP, LoadBalancer, or NodePort
  type: ClusterIP

  # TCP Port for the service
  port: 80

  # TCP Port for the REST API server to listen on
  targetPort: 8080

rest: {}
# Username for the REST API basic auth service. Default is randomly generated
# username: rest-user

# Password for the REST API basic auth service. Default is randomly generated
# password: rest-pass
