---
# Default values for sonobuoy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These global settings relate to sonobuoy
global:
  # Name of a Kubernetes secret with Docker credentials for the private registry
  # registrySecret: ecs-flex-registry

  registry: emccorp

  # Default: "" == Watch ALL namespaces
  watchNamespace: ""

  # Start a sonobuoy cronjob to get the healthcheck of the k8s cluster
  enableHealthcheck: true

# The default docker tag and pull policy for sonobuoy
tag: 0.16.5
pullPolicy: Always

replicaCount: 1

# tag for alpine-curl image should be hard-coded here
alpine_curl_image:
  repository: alpine-curl
  ## tag should only be updated when new version created.
  tag: 7.65

sonobuoy_image:
  repository: sonobuoy
  ## tag should only be updated when new version is created
  tag: v0.14

resources: {}
# We usually recommend not to specify default resources and to leave this
# as a conscious choice for the user. This also increases chances charts run on
# environments with little resources, such as Minikube. If you do want to
# specify resources, uncomment the following lines, adjust them as necessary,
# and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
