---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-install-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-install-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    operator: objectscale-operator
    product: objectscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/component: objectscale-install-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: objectscale-manager
        app.kubernetes.io/component: objectscale-install-controller
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        operator: objectscale-operator
        product: objectscale
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      serviceAccountName: install-controller
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      containers:
        - name: objectscale-install-controller
          resources:
            limits:
              memory: 500M
            requests:
              memory: 250M
          image: {{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ default .Values.tag .Values.image.tag }}
          {{- if .Values.testStartupCommand }}
          command: ["/bin/sh"]
          args: ["-c", "{{ .Values.testStartupCommand }}"]
          {{- end }}
          env:
            - name: OPERATOR_NAME
              value: objectscale-operator
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REST_PORT
              value: {{ .Values.service.targetPort | default 8080 | quote}}
            - name: REST_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rest-credentials
                  key: credentials
            - name: WATCH_NAMESPACE
              {{- if eq .Values.global.watchAllNamespaces true}}
              value: ""
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
              name: http
{{- if .Values.debug }}
            - containerPort: 40000
              name: debug
              protocol: TCP
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
{{- end }}
