---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-install-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-install-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    operator: objectscale-operator
    product: objectscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/component: objectscale-install-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: objectscale-manager
        app.kubernetes.io/component: objectscale-install-controller
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name}}
        operator: objectscale-operator
        product: objectscale
    spec:
      serviceAccountName: install-controller
      containers:
        - name: objectscale-install-controller
          resources:
            limits:
              memory: 500M
            requests:
              memory: 250M
          image: {{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ default .Values.tag .Values.image.tag }}
          env:
            - name: OPERATOR_NAME
              value: objectscale-operator
            - name: WATCH_NAMESPACE
              {{- if eq .Values.global.watchAllNamespaces true}}
              value: ""
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- end }}
          imagePullPolicy: {{ default .Values.pullPolicy .Values.image.pullPolicy }}
