---
# Default values for statefuldaemonset operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These values are overridden when the Atlas operator is included within a subchart
global:

  # The Docker registry hosting containers for the statefuldaemonset operator
  registry: emccorp

  # Specifies if the Operator should watch all namespaces for statefuldaemonset
  # resources or only the namespace that is is deployed in.
  watchAllNamespaces: false

  # Extra labels that will be applied to all resources created by the chart
  labels: {}

image:
  repository: statefuldaemonset-operator
  # tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""

podSecurityContext: {}

securityContext: {}

## Service account name and whether to create it.
serviceAccount:
  create: true
  name: statefuldaemonset-operator

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 1
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
