---
# Default values for ObjectScale IAM service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tag: 0.76.0

# These values may be overridden when the IAM is included within a subchart
global:
  # Name of a Kubernetes secret with container registry credentials for the
  # private registry
  # registrySecret: ecs-flex-registry

  # The container image registry hosting containers for the Atlas operator
  registry: emccorp

# The image configured for the ObjectScale IAM
image:
  pullPolicy: IfNotPresent
  repository: iamsvc
  tag: 3.7.0.0-136266.981d09397fe # rfw-update-this iamsvc-docker-image

# Number of replicas for the ObjectScale IAM deployment
replicaCount: 3

# Liveness and Readiness Probe configurations for the ObjectScale IAM Deployment
livenessProbe:
  probePath: /iamhealthcheck
readinessProbe:
  probePath: /iamhealthcheck/atlas

# Service Configuration for ObjectScale IAM
iam:
  httpPort: 9400
  httpsPort: 443

service:
  # Type of Kubernetes service to create: ClusterIP, NodePort, or LoadBalancer
  type: ClusterIP

  # Specify the service port configuration for the s3 service
  ports:
    - name: https
      port: 443
      targetPort: 9401
      protocol: TCP
    - name: http
      port: 9400
      targetPort: 9402
      protocol: TCP
  # loadBalancerIP:     # select specific load balancer IP of the connection
  # externalHostnames:
  #   - objectscale-vsp.example.com
  # externalIPAddresses:
  #   - 203.0.113.10
  #   - 203.0.113.30
  # externalIPv6Addresses:
  #   - 2001:0db8:0000:0000:0000:0000:0000:0001

tls:
  # Type of certificate signing: SelfSigned, KubernetesSigned, InternallySigned or ExternallySigned
  certificateType: InternallySigned

  certificate: {}
  # publicKey: < server side customer certificate>
  # privateKey: <private key for server side cert>
  # password: # cert password (optional)
  # authority: |-  # (optional)
  #   rootCA: xxxx
  #   intermediateCA:      # provide the intermediate CA here (optional)

  signingRequest:
    # For InternallySigned certificates do not add commonName so that its added in the format as below
    # urn:ocs:ObjectScaleId::service/ServiceName
    # commonName: objectscale-iam
    # email: insertyouremail@example.com.local
    names:
      country: USA
      state: MA
      locality: Hopkinton
      organization: Dell EMC
      organizationalUnit: ObjectScale
    keyAlgorithm: RSA       # algorithm use to generate the key (ex. RSA, ECDSA)
    keySize: 2048           # size of the key in bits (ex. 2048, 4096, 8192)

# Atlas Cluster configuration for ObjectScale persistent Storage
atlas:

  # Disables the affinity rules for the Atlas Cluster, allowing it to run
  # multiple replicas on a single node
  disableAntiAffinity: false

  # Configure the container image
  image:
    pullPolicy: IfNotPresent
    repository: atlas
    tag: 1.1.3 # rfw-update-this atlas-docker-image

  # Persistent storage options for Atlas Cluster
  persistence:
    size: 10Gi

  # Replica count for ObjectScale IAM Atlas Cluster
  replicaCount: 3

  # Atlas pods limits and requests memory setting
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 256Mi
