---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-pod
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    product: {{ required "global.product (e.g. objectscale) is required" .Values.global.product }}
    app: {{ .Release.Name }}-service-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service-pod
        name: {{ .Release.Name }}-service-pod
        release: {{ .Release.Name }}
        remote_access: {{.Values.global.product}}-service-pod
        product: {{ required "global.product (e.g. objectscale) is required" .Values.global.product }}
    spec:
      serviceAccountName: {{ .Release.Name }}-service-pod-sa
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      containers:
      - name: service-pod
        image: {{.Values.global.registry}}/{{.Values.image.repository | replace "base" .Values.global.product}}:{{default .Values.tag .Values.image.tag}}
        imagePullPolicy: {{default .Values.pullPolicy .Values.image.pullPolicy }}
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        env:
        - name: MY_POD_IP
          valueFrom:
              fieldRef:
                fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DELL_EMC_PRODUCT
          value: {{ required "global.product (e.g. objectscale) is required" .Values.global.product }}
        {{- if .Values.global.registrySecret }}
        - name: REGISTRY_SECRET
          value: {{ .Values.global.registrySecret }}
        {{- end }}
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        {{- if .Values.resources }}
        resources:
          {{- if .Values.resources.requests.storage }}
          requests:
             ephemeral-storage: {{ .Values.resources.requests.storage }}
          {{- end }}
          {{- if .Values.resources.limits.storage }}
          limits:
             ephemeral-storage: {{ .Values.resources.limits.storage }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /tmp
          name: host-data
      dnsPolicy: ClusterFirst
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - emptyDir: {}
        name: host-data
      - name: creds-secret-vol
        secret:
          secretName: {{ .Release.Name }}-service-pod-secrets
