apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service-pod 
    release: {{ .Release.Name }}
    product: {{ required "product (e.g. objectscale) is required" .Values.global.product }} 
  name: {{ .Release.Name }}-service-pod 
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 22
    name: ssh
    targetPort: ssh 
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-service-pod
