---
tag: 0.71.2
global:
  registry: emccorp
  performanceProfile: "Small"

# DCM image configuration
image:
  pullPolicy: IfNotPresent
  repository: dcm
  # tag: stable

# Number of replicas for the ObjectScale DCM deployment
replicaCount: 1

# Service Configuration for DCM
service:
  port: 9026
  targetPort: 9026
  type: LoadBalancer

# Liveness and Readiness Probe configurations for the DCM Deployment
livenessProbe:
  probePath: /dcmhealthcheck
readinessProbe:
  probePath: /dcmhealthcheck

# Atlas Cluster configuration for DCM persistent Storage
atlas:
  affinity: false
  image:
    pullPolicy: IfNotPresent
    repository: atlas
    tag: 1.1.3
  persistence:
    size: 1Gi
  # Define the replica if you want to explicitly set it
  # replicaCount: 3
