---
apiVersion: v1
kind: ConfigMap
metadata:
  # TODO: make release name based
  name: influxdb-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-graphql
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
data:
  influxdb.conf: |+
    reporting-disabled = true
    bind-address = "127.0.0.1:8088"
    storage-directory = "/var/lib/influxdb"
    [meta]
      dir = "/var/lib/influxdb/meta"
    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      index-version = "tsi1"

    [retention]
    [shard-precreation]
    [monitor]
      store-enabled = false

    [http]
      bind-address = ":8086"
      flux-enabled = true

    [logging]
    [subscriber]
    [[graphite]]
    [[collectd]]
    [[opentsdb]]
    [[udp]]
    [continuous_queries]
    [tls]
