---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-install-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-install-controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/component: objectscale-install-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: objectscale-manager
        app.kubernetes.io/component: objectscale-install-controller
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name}}
        operator: objectscale-operator
        product: objectscale
    spec:
      serviceAccountName: objectscale-operator
      containers:
        - name: objectscale-install-controller
          image: {{ .Values.global.registry }}/{{ .Values.installcontroller.image.repository }}:{{ default .Values.tag .Values.installcontroller.image.tag }}
          env:
              - name: OPERATOR_NAME
                value: objectscale-operator
          imagePullPolicy: {{ default .Values.pullPolicy .Values.installcontroller.image.pullPolicy }}
