{{- if .Values.logReceiver.type }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-manager-logs-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: ecs-flex-manager
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  fluent-parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name             tail
        Path             /opt/manager/graphql.log
        DB               /var/log/flb.db
        Path_Key         filename
        Parser           manager
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  Off
        Refresh_Interval 10

    [INPUT]
        Name             tail
        Path             /opt/manager/operator.log
        DB               /var/log/flb.db
        Path_Key         filename
        Parser           manager
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  Off
        Refresh_Interval 10

    [FILTER]
        Name record_modifier
        Match *
        Record pod ${POD}
        Record ip ${IP}
        Record namespace ${NAMESPACE}
        Record release_name ${RELEASE_NAME}

{{- if eq .Values.logReceiver.type "Elasticsearch"}}
    [OUTPUT]
        Name            es
        Match           *
        tls             On
        tls.verify      Off
        Type            logEvent
{{- if .Values.logReceiver.user }}
        HTTP_User       {{ .Values.logReceiver.user }}
{{- end }}
{{- if .Values.logReceiver.password }}
        HTTP_Passwd     {{ .Values.logReceiver.password }}
{{- end }}
        Host            {{ .Values.logReceiver.host }}
        Port            {{ .Values.logReceiver.port }}
        Logstash_Format On
        Retry_Limit     False
{{- end }}

{{- if eq .Values.logReceiver.type "Syslog"}}
    [OUTPUT]
        Name            tcp
        Match           *
        tls             On
        tls.verify      Off
        Type            logEvent
        Host            {{ .Values.logReceiver.host }}
        Port            {{ .Values.logReceiver.port }}
        Logstash_Format On
        Retry_Limit     False
{{- end }}
  fluent-parsers.conf: |
    [PARSER]
        Name        manager
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S %z
{{- end }}


