---
apiVersion: v1
kind: ConfigMap
metadata:
    name: objectscale-manager-app-config
    namespace: {{.Release.Namespace}}
    labels:
      app.kubernetes.io/name: objectscale-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/part-of: {{ .Release.Name }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name}}
      operator: objectscale-operator
      product: objectscale
    annotations:
        com.dellemc.kahm.subscribed: "true"
data:
    eventRules: |-
      issueRules:
{{ range $path, $_ :=  .Files.Glob  "alerts/issues/*_issue.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
    eventRemedies: |-
      symptoms:
{{ range $path, $_ :=  .Files.Glob  "alerts/remedies/*_remedies.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
    health: |-
      spec:
        - name: pre-update
          container: {{.Values.global.registry}}/objectscale-manager-pre-update:{{ default .Values.tag .Values.healthChecks.preUpdate.image.tag}}
          serviceaccount: {{ .Release.Name }}-healthchecks
          timelimit: "5m"
          args:
            - -target-version
            - {{ default .Values.tag .Values.healthChecks.preUpdate.image.tag}}
        - name: license-usage
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.licenseUsage.image.repository}}:{{ default .Values.tag .Values.healthChecks.licenseUsage.image.tag}}
          serviceaccount: {{ .Release.Name }}-license-usage
          timelimit: "5m"
          schedule: {{ default "0 */6 * * *" .Values.healthChecks.licenseUsage.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.licenseUsage.disabled}}
        - name: inventory
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.inventory.image.repository}}:{{default .Values.tag .Values.healthChecks.inventory.image.tag}}
          serviceaccount: {{ .Release.Name }}-inventory
          timelimit: "5m"
          schedule: {{ default "0 * * * *" .Values.healthChecks.inventory.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.inventory.disabled}}
          args:
            - -platform
            - {{ .Values.global.platform}}
            - -watch_ns
{{- if eq .Values.global.watchAllNamespaces true}}
            - "" 
{{- else }}
            - metadata.namespace
{{- end }}
        - name: capacity
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.capacity.image.repository}}:{{default .Values.tag .Values.healthChecks.capacity.image.tag}}
          serviceaccount: {{ .Release.Name }}-capacity
          timelimit: "5m"
          schedule: {{ default "0 * * * *" .Values.healthChecks.capacity.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.capacity.disabled}}
          args:
            - -platform
            - {{ .Values.global.platform}}
            - -watch_ns
{{- if eq .Values.global.watchAllNamespaces true}}
            - "" 
{{- else }}
            - metadata.namespace
{{- end }}
            - -window
            - {{ default "60" .Values.healthChecks.capacity.window | quote}}

        - name: performance
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.performance.image.repository}}:{{default .Values.tag .Values.healthChecks.performance.image.tag}}
          serviceaccount: {{ .Release.Name }}-performance
          timelimit: "5m"
          schedule: {{ default "0 * * * *" .Values.healthChecks.performance.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.performance.disabled}}
          args:
            - -platform
            - {{ .Values.global.platform}}
            - -watch_ns
{{- if eq .Values.global.watchAllNamespaces true}}
            - "" 
{{- else }}
            - metadata.namespace
{{- end }}
            - -window
            - {{ default "10" .Values.healthChecks.performance.window | quote}}
        - name: health
          container: {{.Values.global.registry}}/{{ .Values.healthChecks.health.image.repository}}:{{default .Values.tag .Values.healthChecks.health.image.tag}}
          serviceaccount: {{ .Release.Name }}-health
          timelimit: "5m"
          schedule: {{ default "*/5 * * * *" .Values.healthChecks.health.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.health.disabled}}
          args:
            - -platform
            - {{ .Values.global.platform}}
            - -watch_ns
{{- if eq .Values.global.watchAllNamespaces true}}
            - "" 
{{- else }}
            - metadata.namespace
{{- end }}
    eventRemedies: |-
      symptoms:
        - symptomid: DEOS-MGR-1001
          description: Provisioning of the new objectstore failed
          remedies:
            - Check the results of the provisioning job
          serviceaccount: {{ .Release.Name }}-performance
          timelimit: "5m"
          schedule: {{ default "*/5 * * * *" .Values.healthChecks.performance.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.performance.disabled }}
        - name: health
          container: {{.Values.global.registry}}/objectscale-health:{{default .Values.tag .Values.healthChecks.health.image.tag}}
          serviceaccount: {{ .Release.Name }}-health
          timelimit: "5m"
          schedule: {{ default "*/5 * * * *" .Values.healthChecks.health.schedule | quote}}
          disabled: {{ default false .Values.healthChecks.health.disabled }}
    eventRemedies: |-
      symptoms:
        - symptomid: DEOS-MGR-1001
          description: Provisioning of the new objectstore failed
          remedies:
            - Check the results of the provisioning job
