---
# Default values for influxdb operator
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These values are overridden when the Influxdb operator is included within a subchart
global:

  # The Docker registry hosting containers for the influxdb operator
  registry: emccorp

  # Specifies if the Operator should watch all namespaces for influxdb
  # resources or only the namespace that is is deployed in.
  watchAllNamespaces: true

  # Extra labels that will be applied to all resources created by the chart
  labels: {}

  performanceProfile: "Small"

  logging_injection_enabled: true

  rsyslog_enabled: true

image:
  repository: influxdb-operator
  # no need to insert rfw marker here because version comes from global.monitoring_tag
  # tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests: {}
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}
