---
#
# Copyright Â© [2020] Dell Inc. or its subsidiaries.
# All Rights Reserved.
#
# This software contains the intellectual property of Dell Inc.
# or is licensed to Dell Inc. from third parties. Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of Dell Inc. or its subsidiaries.
#
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rsyslog.fullname" . }}-logrotate-config
  labels:
{{ include "rsyslog.labels" . | indent 4}}
data:
  svc: |+
    /var/log/*.log /var/log/*/*/*.log
    {
      size=50M
      maxage 14
      rotate 10
      missingok
      notifempty
      delaycompress
      compress
      dateext
      dateformat .%Y%m%d-%H%M%S
      sharedscripts
      postrotate
              kill -s HUP $(pidof rsyslogd)
      endscript
    }
  logrotate.conf: |+
    # see "man logrotate" for details
    # rotate log files daily
    daily

    # keep rotated logs for 14 days max
    maxage 14

    # rotate 10 by default
    rotate 10

    # use date as a suffix of the rotated file
    dateext

    # Add a dateformat
    dateformat .%Y%m%d-%H%M%S

    # max size is 5 MB
    size 5M

    # Compress log files
    compress

    # comment these to switch compression to use gzip or another
    # compression scheme
    compresscmd /usr/bin/gzip
    uncompresscmd /usr/bin/gunzip

    # rotate logs as root
    su root root

    # RPM packages drop log rotation information into this directory
    include /etc/logrotate.d
