---
tag: 0.61.0
global:
  registry: emccorp
atlas:
  affinity: false
  image:
    pullPolicy: IfNotPresent
    repository: atlas
    tag: v1.1.1
  persistence:
    size: 10Gi
  replicaCount: 3
iamsvc:
  image:
    pullPolicy: IfNotPresent
    repository: iamsvc
    # tag: stable
  livenessProbe:
    probePath: /iamhealthcheck
  readinessProbe:
    probePath: /iamhealthcheck
  replicaCount: 3
  service:
    port: 9400
    type: LoadBalancer
