---
apiVersion: v1
kind: ConfigMap
metadata:
    name: decks-app-config
    namespace: {{.Release.Namespace}}
    labels:
        app.kubernetes.io/name: "decks"
        app.kubernetes.io/version: {{.Values.tag}}
        app.kubernetes.io/instance: {{.Release.Name}}
        app.kubernetes.io/managed-by: nautilus
        helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
        release: {{.Release.Name}}
    annotations:
        com.dellemc.kahm.subscribed: "true"
data:
    eventRules: |-
      issueRules:
{{ range $path, $_ :=  .Files.Glob  "alerts/issues/*_issue.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
      rules:
      - description: send all critical events to SNMP server
      matchon:
      - field: type
        operator: "=="
        value: Critical
      notifiers:
      - objectscale-snmp-notifier
      - description: send all error events to SNMP server
      matchon:
      - field: type
        operator: "=="
        value: Error
      notifiers:
      - objectscale-snmp-notifier
      - description: send all warning events to SNMP server
      matchon:
      - field: type
        operator: "=="
        value: Warning
      notifiers:
      - objectscale-snmp-notifier
    eventRemedies: |-
      symptoms:
        - symptomid: DECKS-1007
          description: Unable to register with Dell EMC Secure Remote Services
          remedies:
            - Make sure a valid Dell EMC license has been applied
            - Make sure the SRS Gateway has not been disabled
            - Verify the correct hostname or IP addr/port was used for
              the SRS gateway
            - Verify the correct Dell EMC customer support account name
              and password were specified
            - Verify the SRS Gateway system is running
            - Check if the SRS gateway has connectivity through the firewall
              to Dell EMC
            - Verify the network connection to the SRS gateway
            - Check the health of the SRS gateway by connecting to the user
              interface
            - Check the status of the SRS Gateway resource in the k8s cluster
            - Make sure the kubernetes cluster has enabled external
              IP provisioning capabilities, (for example LoadBalancer)
        - symptomid: DECKS-1015
          description: Unable to send events to the Dell EMC Secure Remote Service
          remedies:
            - Verify the SRS Gateway system is running
            - Check if the SRS gateway has connectivity through the firewall
              to Dell EMC
            - Verify the network connection to the SRS gateway
            - Check the health of the SRS gateway by connecting to the user
              interface
            - View the logs of the decks and srs-notifier services for any
              additional details
    health: |-
      spec:
        - name: pre-update
          container: {{.Values.global.registry}}/{{.Values.healthChecks.preUpdate.image.repository}}:{{default .Values.tag .Values.healthChecks.preUpdate.image.tag}}
          serviceaccount: {{.Release.Name}}-healthchecks
          timelimit: "5m"
          reason: "pre-update"
          symptomID: "DECKS-HC-1000"
          args:
            - -target-version
            - {{ default .Values.tag .Values.healthChecks.preUpdate.image.tag }}