---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decks-support-store
  labels:
    io.kompose.service: decks-support-store
    app.kubernetes.io/name: decks
    release: {{.Release.Name}}
    name: decks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decks-support-store
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: decks-support-store
    spec:
{{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
{{- end }}
      containers:
      - name: decks-support-store
        env:
{{- if .Values.global.registrySecret }}
        - name: REGISTRY_SECRET
          value: {{ .Values.global.registrySecret }}
{{- end }}
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: decks-support-store-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: decks-support-store-secret
              key: password
        - name: SALT
          valueFrom:
            secretKeyRef:
              name: decks-support-store-secret
              key: salt
        image: {{ .Values.global.registry }}/{{- if .Values.supportStore }}{{- default .Values.supportStore.image.repository "decks-support-store" -}}:{{- default .Values.supportStore.image.version "1.0.0" -}}{{- else }}decks-support-store:1.0.0{{- end}}
        {{- if .Values.supportStore }}
        imagePullPolicy: {{ default .Values.pullPolicy .Values.supportStore.image.pullPolicy }}
        {{- else }}
        imagePullPolicy: Always
        {{- end}}
        command: ["/bin/sh", "-c"]
        args: ["chmod +x /usr/local/bin/*.sh;
                sh /usr/local/bin/run-nginx.sh;
                nginx -g 'daemon off;'"]
        ports:
        {{- if .Values.supportStore }}
        - containerPort: {{ .Values.supportStore.containerPort }}
        {{- else }}
        - containerPort: 7443
        {{- end }}
        resources: {}
        volumeMounts:
        - mountPath: /opt/secure/data
          name: decks-support-store-claim0
      restartPolicy: Always
      volumes:
      - name: decks-support-store-claim0
        persistentVolumeClaim:
          claimName: decks-support-store-claim0
