apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: decks-webdav
  name: decks-webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decks-webdav
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: decks-webdav
    spec:
{{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
{{- end }}
      containers:
      - name: decks-webdav
        env:
{{- if .Values.global.registrySecret }}
        - name: REGISTRY_SECRET
          value: {{ .Values.global.registrySecret }}
{{- end }}
        - name: AUTH_TYPE
          value: Digest
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: decks-webdav-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: decks-webdav-secret
              key: password
        image: {{ .Values.global.registry }}/{{.Values.webdav.image.repository }}:{{ .Values.webdav.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["chmod + x /usr/local/bin/*.sh;
                sh /usr/local/bin/run-webdav.sh"]
        ports:
        - containerPort: {{ .Values.webdav.containerPort }}
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/dav
          name: decks-webdav-claim0    
      restartPolicy: Always
      volumes:
      - name: decks-webdav-claim0
        persistentVolumeClaim:
          claimName: decks-webdav-claim0