---
#
# Copyright Â© [2020] Dell Inc. or its subsidiaries.
# All Rights Reserved.
#
# This software contains the intellectual property of Dell Inc.
# or is licensed to Dell Inc. from third parties. Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of Dell Inc. or its subsidiaries.
#
#

## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/

global:
  registry: emccorp
  # watchAllNamespaces:
  # - false: webhook is configured to select pods only in logging-injector namespace
  #          using labels `app.kubernetes.io/namespace: <pod namespace>`
  #          and `objectscale.dellemc.com/logging-inject: true`
  # - true: webhook is configured to select all pods with label `objectscale.dellemc.com/logging-inject`
  #         in all namespaces
  watchAllNamespaces: true

replicas: 1

image:
  repository: logging-injector
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 256Mi

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

config:
  logVolumeName: "log"
