---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.Release.Name}}-app-config
    namespace: {{.Release.namespace}}
    labels:
      app.kubernetes.io/name: {{.Release.Name}}
      app.kubernetes.io/version: {{.Values.tag}}
      app.kubernetes.io/instance: {{.Release.Name}}
      app.kubernetes.io/managed-by: {{.Release.Service}}
      helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
      product: objectscale
      release: {{.Release.Name}}
    annotations:
        com.dellemc.kahm.subscribed: "true"
data:
    eventRules: |-
      issueRules:
        - description: "No data is pushed to the monitoring framework for the last 30 minutes"
          name: "MonitoringHealth"
          defaultAutoClearTimeOut: 60
          issueCategory: Auto
          matchOnList:
            - matchon:
                - label: SymptomID
                  value: 4019
                - field: type
                  value: Critical
          notifiers:
            - objectscale-srs
        - description: "Hard quota exceeded for this bucket"
          name: "BucketHardQuota"
          defaultAutoClearTimeOut: 60
          issueCategory: Auto
          matchOnList:
            - matchon:
                - label: SymptomID
                  value: 1006
                - field: type
                  value: Error
          notifiers:
            - objectscale-srs
        - description: "Memory table size for process is less than specified threshold"
          name: "ProcessMemoryTableFreeSpacePercent"
          defaultAutoClearTimeOut: 60
          issueCategory: Auto
          matchOnList:
            - matchon:
                - label: SymptomID
                  value: 1354
                - field: type
                  value: Error
          notifiers:
            - objectscale-srs
        - description: "SSD read cache auto clean up failed when capacity full and fall back to memory cache"
          name: "SSDReadCacheCapacityFailure"
          defaultAutoClearTimeOut: 60
          issueCategory: Auto
          matchOnList:
            - matchon:
                - label: SymptomID
                  value: 1392
                - field: type
                  value: Error
          notifiers:
            - objectscale-srs
    eventRemedies: |-
      symptoms:
        - symptomid: 1006
          description: Hard quota exceeded for this bucket
          remedies:
            - Free up space in the bucket
        - symptomid: 4019
          description: No data is pushed to the monitoring framework for the last 30 minutes
          remedies:
            - KB https://support.emc.com/kb/536249
        - symptomid: 1354
          description: Memory table size for process is less than specified threshold
          remedies:
            - KB https://support.emc.com/kb/530081
    health: |-
      spec:
        healthchecks:
          fieldcolumns:
            - name: deos-hc
              fields:
              - name: name
                type: string
              - name: description
                type: string
              - name: enabled
                type: boolean
              - name: schedule
                type: string
              - name: latestSuccess
                type: date
              - name: latestFailure
                type: date
              - name: message
                type: string
          name: objectstore-healthchecks
        healthcheckstatus:
          deos-hc:
            overview: none
            rows:
            - name:
              description:
              enabled: true
              schedule: Every 6 hours
              latestSuccess:
              latestFailure:
              message:
