---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-iam
  labels:
    {{- include "iam.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "iam.selectorLabels" . | nindent 8 }}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      containers:
      - name: iam
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "atlas,flex,dns"
        - name: ATLAS_SERVICE_HOSTNAME
          value: {{ include "iam.name" . }}-atlas-client
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_OBJECTSCALE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: {{ default  .Values.global.registry .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Values.tag .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: https
            containerPort: 9401
            protocol: TCP
          - name: http
            containerPort: 9402
            protocol: TCP
        livenessProbe:
            httpGet:
                path: {{ .Values.livenessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 60 }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 60 }}
        readinessProbe:
            httpGet:
                path: {{ .Values.readinessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 60 }}
            initialDelaySeconds: {{ .Values.readinessProbe.iinitialDelaySeconds | default 60 }}
        volumeMounts:
        - name: log
          mountPath: /opt/storageos/logs
        - name: tls-secrets
          mountPath: "/etc/nginx/ssl"
      volumes:
      - name: log
        emptyDir: {}
      - name: tls-secrets
        secret:
          secretName: objectscale-iam-tls
