---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedsvc
  labels:
    {{- include "fedsvc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fedsvc.replicaCount }}
  selector:
    matchLabels:
      {{- include "fedsvc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fedsvc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "federation"
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: fedsvc
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: {{ default  .Values.global.registry .Values.fedsvc.image.registry }}/{{ .Values.fedsvc.image.repository }}:{{ default .Values.tag .Values.fedsvc.image.tag }}
        imagePullPolicy: {{ .Values.fedsvc.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 9501 
            protocol: TCP
        livenessProbe:
            httpGet:
                path: {{ .Values.fedsvc.livenessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.fedsvc.livenessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.fedsvc.livenessProbe.periodSeconds | default 60 }}
        readinessProbe:
            httpGet:
                path: {{ .Values.fedsvc.readinessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.fedsvc.readinessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.fedsvc.readinessProbe.periodSeconds | default 60 }}


